steps:
  - id: build-backend
    name: "docker"
    args:
      - build
      - --file=./infrastructure/Dockerfile
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .
  - id: push-backend
    name: "docker"
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ["build-backend"]
  - id: "apply-migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - "-c"
      - "/buildstep/execute.sh -i $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA -e DATABASE_URL=$$DATABASE_URL -s $_CLOUDSQL_INSTANCE_FULL_NAME -- yarn prisma migrate deploy"
    secretEnv: ["DATABASE_URL"]
    waitFor: ["push-backend"]
  - id: deploy-backend
    name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - rakucia-server
      - --quiet
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --service-account=$_SERVICE_ACCOUNT
      - --add-cloudsql-instances=$_CLOUDSQL_INSTANCE_FULL_NAME
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --concurrency=40
      - --cpu=1
      - --memory=512Mi
      - --max-instances=3
      - --min-instances=1
      - --no-use-http2
      - --allow-unauthenticated
      - --no-cpu-throttling
      - --ingress=all
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID
      - --update-secrets=DATABASE_URL=DATABASE_URL:latest
      - --update-secrets=RAKUTEN_ID=RAKUTEN_ID:latest
      - --update-secrets=RAKUTEN_SECRET=RAKUTEN_SECRET:latest
      - --update-secrets=CHANNEL_ACCESS_TOKEN=CHANNEL_ACCESS_TOKEN:latest
      - --update-secrets=CHANNEL_SECRET=CHANNEL_SECRET:latest
      - --update-secrets=LIFF_URL=LIFF_URL:latest
    secretEnv: ["RAKUTEN_ID", "RAKUTEN_SECRET", "CHANNEL_ACCESS_TOKEN", "CHANNEL_SECRET", "LIFF_URL"]
    waitFor: ["apply-migrations"]
timeout: 2000s
substitutions:
  _REGION: by-terraform
  _CLOUDSQL_INSTANCE_FULL_NAME: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/RAKUTEN_ID/versions/latest
      env: RAKUTEN_ID
    - versionName: projects/$PROJECT_ID/secrets/RAKUTEN_SECRET/versions/latest
      env: RAKUTEN_SECRET
    - versionName: projects/$PROJECT_ID/secrets/CHANNEL_ACCESS_TOKEN/versions/latest
      env: CHANNEL_ACCESS_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/CHANNEL_SECRET/versions/latest
      env: CHANNEL_SECRET
    - versionName: projects/$PROJECT_ID/secrets/LIFF_URL/versions/latest
      env: LIFF_URL

# https://cloud.google.com/build/docs/building/build-containers
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
